### ISSUE TITLE
youtube & airflow key

### ISSUE THREAD

**Issue by louis70109** [ChickenBenny/Airflow-Learning-English-tool#1]
小建議~兩個KEY可以在README下方寫步驟教大家如何建立，

但放在CODE裡面會比較有資安問題喔~

https://github.com/ChickenBenny/Airflow-Learning-English-tool/blob/main/develop_dmo/youtube_api.ipynb?short_path=31c34d5#L11
https://github.com/ChickenBenny/Airflow-Learning-English-tool/blob/main/.env#L10

**Comment by ChickenBenny** [comment]
!! 好的感謝你的建議，我晚點會修改~
下次push前會注意這些小細節，感恩!
